version: '3.7'
services:
  proback:
    container_name: proback
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build:
        context: ./ 
    ports:
      - "3000:3000"
